---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    commands:
      - git fetch --tags
      - apk add coreutils
      - docker buildx create --driver docker-container --platform linux/amd64 --buildkitd-flags "--allow-insecure-entitlement security.insecure" --name local --use unix:///var/outer-run/docker.sock
      - docker buildx inspect --bootstrap
    privileged: true
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: build-pull-request
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: build-and-publish
    image: autonomy/build-container:latest
    pull: always
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
      - make PUSH=true
    when:
      event:
        exclude:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: build-release
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make release
    when:
      event:
        - tag
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - sha256
        - sha512
      draft: true
      files:
        - _out/*
    when:
      event:
        - tag

volumes:
  - name: docker-socket
    temp: {}
  - name: outerdockersock
    host:
      path: /var/ci-docker
  - name: docker
    temp: {}
---
kind: pipeline
type: kubernetes
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
---
kind: signature
hmac: 9e465020b2d4d694c23f176e05cef4c7da9bb75acb2a51a230bef7343f4ee18c

...
